#!/bin/sh

# Enable module updates repo
sed -i "s/enabled=0/enabled=1/g" /etc/yum.repos.d/modules-updates.repo

echo ""
echo "We have travelled in time a week into the future!"
echo "Now we can test that update works!"

